import type { AppData, Task, TimeBlock } from "./types";
import { getWeekDays } from "./date";

export function makeSampleData(): AppData {
  const days = getWeekDays(0);
  const nextWeek = getWeekDays(1);
  const mon = days[0], tue = days[1], wed = days[2], thu = days[3];
  const fri = days[4], sat = days[5], sun = days[6];
  const nextMon = nextWeek[0], nextTue = nextWeek[1], nextThu = nextWeek[3];

  const tasks: Task[] = [
    {
      id: "task-db-design",
      name: "数据库设计讨论",
      date: mon.key,
      status: "todo",
      subtasks: [
        { id: "sub-db1", name: "Review ER 图", done: true },
        { id: "sub-db2", name: "确认索引策略", done: false },
      ],
      priority: "important",
    },
    {
      id: "task-client-meeting",
      name: "客户沟通会议",
      date: mon.key,
      status: "todo",
      subtasks: [{ id: "sub-cm1", name: "准备演示材料", done: false }],
      priority: "urgent-important",
    },
    {
      id: "task-morning-run",
      name: "晨跑",
      date: mon.key,
      status: "done",
      subtasks: [],
      priority: "important",
    },
    {
      id: "task-meditation",
      name: "冥想放松",
      date: mon.key,
      status: "done",
      subtasks: [],
      priority: "neither",
    },
    {
      id: "task-react-docs",
      name: "学习 React 官方文档",
      date: tue.key,
      status: "todo",
      subtasks: [{ id: "sub-rd1", name: "Hooks 章节", done: false }],
      priority: "important",
    },
    {
      id: "task-english",
      name: "英语听力练习",
      date: tue.key,
      status: "done",
      subtasks: [],
      priority: "important",
    },
    {
      id: "task-grocery",
      name: "超市采购",
      date: tue.key,
      status: "todo",
      subtasks: [
        { id: "sub-gr1", name: "食材", done: true },
        { id: "sub-gr2", name: "日用品", done: false },
      ],
      priority: "urgent",
    },
    {
      id: "task-swimming",
      name: "游泳",
      date: tue.key,
      status: "todo",
      subtasks: [],
      priority: "neither",
    },
    {
      id: "task-req-doc",
      name: "项目需求文档编写",
      date: wed.key,
      status: "todo",
      subtasks: [
        { id: "sub-req1", name: "功能范围", done: true },
        { id: "sub-req2", name: "用户故事", done: false },
        { id: "sub-req3", name: "验收标准", done: false },
      ],
      priority: "urgent-important",
    },
    {
      id: "task-code-review",
      name: "代码架构评审",
      date: wed.key,
      status: "todo",
      subtasks: [],
      priority: "important",
    },
    {
      id: "task-system-design",
      name: "阅读《系统设计面试》",
      date: wed.key,
      status: "todo",
      subtasks: [{ id: "sub-sd1", name: "第 4 章 分布式系统", done: false }],
      priority: "important",
    },
    {
      id: "task-gym",
      name: "健身房力量训练",
      date: wed.key,
      status: "todo",
      subtasks: [],
      priority: "important",
    },
    {
      id: "task-dinner-prep",
      name: "晚餐准备",
      date: wed.key,
      status: "todo",
      subtasks: [],
      priority: "urgent",
    },
    {
      id: "task-retrospective",
      name: "项目复盘",
      date: wed.key,
      status: "todo",
      subtasks: [
        { id: "sub-retro1", name: "整理 Sprint 数据", done: true },
        { id: "sub-retro2", name: "改进项清单", done: false },
      ],
      priority: "urgent-important",
    },
    {
      id: "task-frontend-dev",
      name: "前端页面开发",
      date: thu.key,
      status: "todo",
      subtasks: [
        { id: "sub-fe1", name: "完成布局组件", done: true },
        { id: "sub-fe2", name: "接入 API 数据", done: false },
        { id: "sub-fe3", name: "响应式调试", done: false },
      ],
      priority: "important",
    },
    {
      id: "task-ai-homework",
      name: "AI 课程作业",
      date: thu.key,
      status: "todo",
      subtasks: [{ id: "sub-ai1", name: "Transformer 论文阅读", done: false }],
      priority: "important",
    },
    {
      id: "task-yoga",
      name: "瑜伽课程",
      date: thu.key,
      status: "todo",
      subtasks: [],
      priority: "important",
    },
    {
      id: "task-haircut",
      name: "理发",
      date: thu.key,
      status: "todo",
      subtasks: [],
      priority: "urgent",
    },
    {
      id: "task-backup",
      name: "备份重要文件",
      date: thu.key,
      status: "todo",
      subtasks: [],
      priority: "urgent-important",
    },
    {
      id: "task-api-integration",
      name: "后端 API 接口联调",
      date: fri.key,
      status: "todo",
      subtasks: [
        { id: "sub-api1", name: "用户模块接口", done: true },
        { id: "sub-api2", name: "数据同步接口", done: false },
      ],
      priority: "urgent-important",
    },
    {
      id: "task-blog",
      name: "技术博客写作",
      date: fri.key,
      status: "todo",
      subtasks: [
        { id: "sub-blog1", name: "完成初稿", done: false },
        { id: "sub-blog2", name: "配图", done: false },
      ],
      priority: "important",
    },
    {
      id: "task-weekly-report",
      name: "周报撰写",
      date: fri.key,
      status: "todo",
      subtasks: [],
      priority: "important",
    },
    {
      id: "task-rent",
      name: "交房租",
      date: fri.key,
      status: "todo",
      subtasks: [],
      priority: "urgent",
    },
    {
      id: "task-demo-prep",
      name: "产品演示准备",
      date: sat.key,
      status: "todo",
      subtasks: [
        { id: "sub-demo1", name: "准备演示环境", done: false },
        { id: "sub-demo2", name: "演练演示流程", done: false },
      ],
      priority: "urgent-important",
    },
    {
      id: "task-hiking",
      name: "周末徒步",
      date: sat.key,
      status: "todo",
      subtasks: [],
      priority: "important",
    },
    {
      id: "task-movie",
      name: "周末电影",
      date: sat.key,
      status: "todo",
      subtasks: [],
      priority: "neither",
    },
    {
      id: "task-clean-desk",
      name: "整理书桌",
      date: sun.key,
      status: "todo",
      subtasks: [],
      priority: "neither",
    },
    {
      id: "task-next-plan",
      name: "制定下周计划",
      date: sun.key,
      status: "todo",
      subtasks: [
        { id: "sub-np1", name: "回顾本周完成情况", done: false },
        { id: "sub-np2", name: "确定下周目标", done: false },
      ],
      priority: "important",
    },
    {
      id: "task-fcpx",
      name: "Final Cut Pro 学习",
      date: sun.key,
      status: "todo",
      subtasks: [],
      priority: "neither",
    },
    {
      id: "task-doc-org",
      name: "项目文档整理",
      date: nextMon.key,
      status: "todo",
      subtasks: [{ id: "sub-do1", name: "API 文档归档", done: false }],
      priority: "important",
    },
    {
      id: "task-data-analysis",
      name: "数据分析报告",
      date: nextTue.key,
      status: "todo",
      subtasks: [],
      priority: "important",
    },
    {
      id: "task-team-building",
      name: "团队建设活动",
      date: nextThu.key,
      status: "todo",
      subtasks: [{ id: "sub-tb1", name: "确认场地", done: false }],
      priority: "neither",
    },
    {
      id: "task-monthly-review",
      name: "月度复盘",
      date: null,
      status: "todo",
      subtasks: [{ id: "sub-mr1", name: "汇总本月数据", done: false }],
      pinned: true,
      priority: "important",
    },
    {
      id: "task-side-project",
      name: "个人项目：AI 助手",
      date: null,
      status: "todo",
      subtasks: [
        { id: "sub-sp1", name: "设计对话流程", done: false },
        { id: "sub-sp2", name: "实现工具调用", done: false },
      ],
      pinned: true,
      priority: "important",
    },
    {
      id: "task-read-book",
      name: "《人类简史》阅读",
      date: null,
      status: "todo",
      subtasks: [{ id: "sub-rb1", name: "第三部 笔记", done: false }],
      priority: "neither",
    },
  ];

  const timeBlocks: TimeBlock[] = [
    // ---- Monday ----
    {
      id: "bl-1",
      taskId: "task-morning-run",
      name: "晨跑",
      date: mon.key,
      start: 7 * 60,
      end: 7 * 60 + 45,
      category: "fitness",
      location: "深圳湾公园",
      done: true,
      status: "scheduled",
    },
    {
      id: "bl-2",
      taskId: "task-db-design",
      name: "数据库设计讨论",
      date: mon.key,
      start: 9 * 60,
      end: 10 * 60 + 30,
      category: "work",
      location: "会议室 A",
      done: false,
      status: "scheduled",
    },
    {
      id: "bl-3",
      taskId: "task-client-meeting",
      name: "客户沟通会议",
      date: mon.key,
      start: 11 * 60,
      end: 12 * 60,
      category: "work",
      location: "腾讯会议",
      done: false,
      status: "scheduled",
    },
    {
      id: "bl-4",
      name: "午餐",
      date: mon.key,
      start: 12 * 60,
      end: 13 * 60,
      category: "life",
      location: "楼下食堂",
      done: false,
      status: "scheduled",
    },
    {
      id: "bl-5",
      name: "项目需求整理",
      date: mon.key,
      start: 14 * 60,
      end: 15 * 60 + 30,
      category: "work",
      location: "工位",
      done: false,
      status: "scheduled",
    },
    {
      id: "bl-6",
      taskId: "task-meditation",
      name: "冥想放松",
      date: mon.key,
      start: 15 * 60 + 30,
      end: 16 * 60,
      category: "rest",
      location: "休息区",
      done: true,
      status: "scheduled",
    },
    {
      id: "bl-7",
      taskId: "task-react-docs",
      name: "学习 React 文档",
      date: mon.key,
      start: 20 * 60,
      end: 21 * 60,
      category: "study",
      location: "家",
      done: false,
      status: "scheduled",
    },
    // ---- Tuesday ----
    {
      id: "bl-8",
      taskId: "task-english",
      name: "英语听力练习",
      date: tue.key,
      start: 7 * 60 + 30,
      end: 8 * 60 + 30,
      category: "study",
      location: "家",
      done: true,
      status: "scheduled",
    },
    {
      id: "bl-9",
      taskId: "task-frontend-dev",
      name: "前端页面开发",
      date: tue.key,
      start: 9 * 60,
      end: 11 * 60,
      category: "work",
      location: "工位",
      done: false,
      status: "scheduled",
    },
    {
      id: "bl-10",
      name: "午餐",
      date: tue.key,
      start: 12 * 60,
      end: 13 * 60,
      category: "life",
      location: "公司食堂",
      done: false,
      status: "scheduled",
    },
    {
      id: "bl-11",
      taskId: "task-grocery",
      name: "超市采购",
      date: tue.key,
      start: 15 * 60,
      end: 16 * 60,
      category: "life",
      location: "盒马鲜生",
      done: false,
      status: "scheduled",
    },
    {
      id: "bl-12",
      taskId: "task-swimming",
      name: "游泳",
      date: tue.key,
      start: 17 * 60,
      end: 18 * 60,
      category: "fitness",
      location: "体育中心",
      done: false,
      status: "scheduled",
    },
    {
      id: "bl-13",
      taskId: "task-system-design",
      name: "阅读《系统设计面试》",
      date: tue.key,
      start: 20 * 60,
      end: 21 * 60 + 30,
      category: "study",
      location: "家",
      done: false,
      status: "scheduled",
    },
    // ---- Wednesday ----
    {
      id: "bl-14",
      taskId: "task-req-doc",
      name: "项目需求文档编写",
      date: wed.key,
      start: 9 * 60,
      end: 11 * 60,
      category: "work",
      location: "工位",
      done: false,
      status: "scheduled",
    },
    {
      id: "bl-15",
      taskId: "task-code-review",
      name: "代码架构评审",
      date: wed.key,
      start: 11 * 60,
      end: 12 * 60,
      category: "work",
      location: "会议室 B",
      done: false,
      status: "scheduled",
    },
    {
      id: "bl-16",
      name: "午餐",
      date: wed.key,
      start: 12 * 60,
      end: 13 * 60,
      category: "life",
      location: "楼下食堂",
      done: false,
      status: "scheduled",
    },
    {
      id: "bl-17",
      taskId: "task-retrospective",
      name: "项目复盘",
      date: wed.key,
      start: 14 * 60,
      end: 15 * 60 + 30,
      category: "work",
      location: "会议室 A",
      done: false,
      status: "scheduled",
    },
    {
      id: "bl-18",
      taskId: "task-gym",
      name: "健身房力量训练",
      date: wed.key,
      start: 16 * 60,
      end: 17 * 60,
      category: "fitness",
      location: "健身房",
      done: false,
      status: "scheduled",
    },
    {
      id: "bl-19",
      taskId: "task-dinner-prep",
      name: "晚餐准备",
      date: wed.key,
      start: 18 * 60,
      end: 19 * 60,
      category: "life",
      location: "家",
      done: false,
      status: "scheduled",
    },
    {
      id: "bl-20",
      name: "AI 课程",
      date: wed.key,
      start: 20 * 60,
      end: 21 * 60 + 30,
      category: "study",
      location: "家",
      done: false,
      status: "scheduled",
    },
    // ---- Thursday ----
    {
      id: "bl-21",
      taskId: "task-api-integration",
      name: "后端 API 接口联调",
      date: thu.key,
      start: 9 * 60,
      end: 11 * 60,
      category: "work",
      location: "工位",
      done: false,
      status: "scheduled",
    },
    {
      id: "bl-22",
      taskId: "task-backup",
      name: "备份重要文件",
      date: thu.key,
      start: 11 * 60,
      end: 12 * 60,
      category: "work",
      location: "工位",
      done: false,
      status: "scheduled",
    },
    {
      id: "bl-23",
      name: "午餐",
      date: thu.key,
      start: 12 * 60,
      end: 13 * 60,
      category: "life",
      location: "公司食堂",
      done: false,
      status: "scheduled",
    },
    {
      id: "bl-24",
      taskId: "task-haircut",
      name: "理发",
      date: thu.key,
      start: 14 * 60,
      end: 15 * 60,
      category: "life",
      location: "楼下理发店",
      done: false,
      status: "scheduled",
    },
    {
      id: "bl-25",
      taskId: "task-yoga",
      name: "瑜伽课程",
      date: thu.key,
      start: 16 * 60,
      end: 17 * 60,
      category: "fitness",
      location: "瑜伽馆",
      done: false,
      status: "scheduled",
    },
    {
      id: "bl-26",
      taskId: "task-fcpx",
      name: "Final Cut Pro 学习",
      date: thu.key,
      start: 19 * 60,
      end: 21 * 60,
      category: "study",
      location: "家",
      done: false,
      status: "scheduled",
    },
    // ---- Friday ----
    {
      id: "bl-27",
      taskId: "task-blog",
      name: "技术博客写作",
      date: fri.key,
      start: 9 * 60,
      end: 11 * 60,
      category: "study",
      location: "工位",
      done: false,
      status: "scheduled",
    },
    {
      id: "bl-28",
      taskId: "task-weekly-report",
      name: "周报撰写",
      date: fri.key,
      start: 11 * 60,
      end: 12 * 60,
      category: "work",
      location: "工位",
      done: false,
      status: "scheduled",
    },
    {
      id: "bl-29",
      name: "午餐",
      date: fri.key,
      start: 12 * 60,
      end: 13 * 60,
      category: "life",
      location: "楼下食堂",
      done: false,
      status: "scheduled",
    },
    {
      id: "bl-30",
      taskId: "task-rent",
      name: "交房租",
      date: fri.key,
      start: 14 * 60,
      end: 14 * 60 + 30,
      category: "life",
      location: "手机银行",
      done: false,
      status: "scheduled",
    },
    {
      id: "bl-31",
      taskId: "task-demo-prep",
      name: "产品演示准备",
      date: fri.key,
      start: 15 * 60,
      end: 17 * 60,
      category: "work",
      location: "工位",
      done: false,
      status: "scheduled",
    },
    {
      id: "bl-32",
      taskId: "task-movie",
      name: "周末电影",
      date: fri.key,
      start: 19 * 60,
      end: 21 * 60,
      category: "rest",
      location: "家",
      done: false,
      status: "scheduled",
    },
    // ---- Saturday ----
    {
      id: "bl-33",
      taskId: "task-hiking",
      name: "周末徒步",
      date: sat.key,
      start: 8 * 60,
      end: 10 * 60,
      category: "fitness",
      location: "塘朗山",
      done: false,
      status: "scheduled",
    },
    {
      id: "bl-34",
      name: "采购",
      date: sat.key,
      start: 10 * 60 + 30,
      end: 12 * 60,
      category: "life",
      location: "超市",
      done: false,
      status: "scheduled",
    },
    {
      id: "bl-35",
      taskId: "task-demo-prep",
      name: "产品演示彩排",
      date: sat.key,
      start: 14 * 60,
      end: 16 * 60,
      category: "work",
      location: "家",
      done: false,
      status: "scheduled",
    },
    {
      id: "bl-36",
      taskId: "task-movie",
      name: "周末电影",
      date: sat.key,
      start: 19 * 60,
      end: 21 * 60,
      category: "rest",
      location: "家",
      done: false,
      status: "scheduled",
    },
    // ---- Sunday ----
    {
      id: "bl-37",
      taskId: "task-clean-desk",
      name: "整理书桌",
      date: sun.key,
      start: 9 * 60,
      end: 10 * 60,
      category: "life",
      location: "家",
      done: false,
      status: "scheduled",
    },
    {
      id: "bl-38",
      taskId: "task-next-plan",
      name: "制定下周计划",
      date: sun.key,
      start: 10 * 60,
      end: 12 * 60,
      category: "work",
      location: "家",
      done: false,
      status: "scheduled",
    },
    {
      id: "bl-39",
      name: "冥想放松",
      date: sun.key,
      start: 14 * 60,
      end: 15 * 60,
      category: "rest",
      location: "阳台",
      done: false,
      status: "scheduled",
    },
    {
      id: "bl-40",
      taskId: "task-fcpx",
      name: "Final Cut Pro 学习",
      date: sun.key,
      start: 15 * 60,
      end: 17 * 60,
      category: "study",
      location: "家",
      done: false,
      status: "scheduled",
    },
  ];

  return { version: 1, tasks, timeBlocks };
}
