"""Breakdown golden set：AI 任务拆解 record-only 回归集。

`--split breakdown` 才执行本组；只记录宽松检查比率（任务数 1-3、子任务
0-5、名称非空、错误路径契约），不设门禁阈值，不并入 open/heldout/all。
语言跟随等软质量靠快照逐条人工复核。
"""

from __future__ import annotations

from app.golden_ai_cases import GOLDEN_ANCHOR_DATE


BREAKDOWN_GOLDEN_VERSION = "0.1.0"

BREAKDOWN_GOLDEN_CASES: list[dict[str, object]] = [
    {
        "id": "bd01",
        "kind": "breakdown",
        "name": "单项目计划拆解",
        "description": "一个毕业论文项目拆为 1-3 个任务，子任务为可执行步骤。",
        "input": "完成毕业论文：文献调研、撰写开题报告、与导师开会讨论",
        "source": "synthetic",
        "added_in": "0.1.0",
        "rationale": "最常见形态：单一项目、多步骤，验证拆解粒度与任务数量契约。",
        "today": GOLDEN_ANCHOR_DATE,
        "plan": "完成毕业论文：文献调研、撰写开题报告、与导师开会讨论",
    },
    {
        "id": "bd02",
        "kind": "breakdown",
        "name": "多项目计划拆解",
        "description": "一周内三个并列事项应拆为不超过 3 个任务。",
        "input": "这周要推进三件事：准备周会分享、修复登录页的 bug、制定跑步训练计划",
        "source": "synthetic",
        "added_in": "0.1.0",
        "rationale": "多项目并列输入，验证任务数量上限契约（1-3）不被突破。",
        "today": GOLDEN_ANCHOR_DATE,
        "plan": "这周要推进三件事：准备周会分享、修复登录页的 bug、制定跑步训练计划",
    },
    {
        "id": "bd03",
        "kind": "breakdown",
        "name": "英文计划语言跟随",
        "description": "英文输入应输出英文任务名与子任务（结构检查 + 快照人工复核语言）。",
        "input": "Build a personal website: design the layout, implement the pages, deploy to Vercel",
        "source": "synthetic",
        "added_in": "0.1.0",
        "rationale": "prompt 契约要求输出语言跟随输入，英文输入回归。",
        "today": GOLDEN_ANCHOR_DATE,
        "plan": "Build a personal website: design the layout, implement the pages, deploy to Vercel",
    },
    {
        "id": "bd04",
        "kind": "breakdown",
        "name": "单任务五步子任务",
        "description": "单个发布项目带五个明确步骤，子任务数量不得超过 5。",
        "input": "准备产品发布：列出功能清单、撰写发布公告、准备宣传截图、检查文档链接、通知内测用户",
        "source": "synthetic",
        "added_in": "0.1.0",
        "rationale": "子任务数量契约上界（0-5）：输入本身含 5 个步骤，不得膨胀。",
        "today": GOLDEN_ANCHOR_DATE,
        "plan": "准备产品发布：列出功能清单、撰写发布公告、准备宣传截图、检查文档链接、通知内测用户",
    },
    {
        "id": "bd05",
        "kind": "breakdown",
        "name": "跨行多任务长计划",
        "description": "换行分隔的多行项目计划，任务数量仍收敛在 1-3。",
        "input": "搬家计划：\n整理物品并分类打包\n联系搬家公司比价\n新居水电网络开通",
        "source": "synthetic",
        "added_in": "0.1.0",
        "rationale": "多行输入的解析稳定性（_split_plan_text 兜底按换行切分）。",
        "today": GOLDEN_ANCHOR_DATE,
        "plan": "搬家计划：\n整理物品并分类打包\n联系搬家公司比价\n新居水电网络开通",
    },
    {
        "id": "bd06",
        "kind": "breakdown",
        "name": "空输入错误契约",
        "description": "空计划不调用 LLM，固定返回 source=none 与「输入为空」。",
        "input": "",
        "source": "fault_sample",
        "added_in": "0.1.0",
        "rationale": "确定性错误路径：空输入在 provider 解析前短路返回。",
        "today": GOLDEN_ANCHOR_DATE,
        "plan": "",
        "expect_error": "输入为空",
    },
    {
        "id": "bd07",
        "kind": "breakdown",
        "name": "非项目闲聊拒绝",
        "description": "闲聊语料不含项目计划，应返回固定 error 文案而非编造任务。",
        "input": "你好，今天天气怎么样？",
        "source": "fault_sample",
        "added_in": "0.1.0",
        "rationale": "T-037 错误契约回归：非项目输入固定返回「未识别到有效项目计划」。",
        "today": GOLDEN_ANCHOR_DATE,
        "plan": "你好，今天天气怎么样？",
        "expect_error": "未识别到有效项目计划",
    },
    {
        "id": "bd08",
        "kind": "breakdown",
        "name": "纯数字无效输入",
        "description": "纯数字串无任何项目语义，应走固定 error 拒答路径。",
        "input": "12345 67890",
        "source": "fault_sample",
        "added_in": "0.1.0",
        "rationale": "与 bd07 同契约但输入形态不同（无汉字），防止仅靠汉字判定。",
        "today": GOLDEN_ANCHOR_DATE,
        "plan": "12345 67890",
        "expect_error": "未识别到有效项目计划",
    },
    {
        "id": "bd09",
        "kind": "breakdown",
        "name": "中英混合计划",
        "description": "中文主体夹英文术语的备考计划，结构检查 + 快照人工复核语言选择。",
        "input": "准备 final exam：复习 lecture notes、刷 past papers、整理错题本",
        "source": "synthetic",
        "added_in": "0.1.0",
        "rationale": "混合语言输入的拆解稳定性与语言跟随倾向观察样本。",
        "today": GOLDEN_ANCHOR_DATE,
        "plan": "准备 final exam：复习 lecture notes、刷 past papers、整理错题本",
    },
    {
        "id": "bd10",
        "kind": "breakdown",
        "name": "简短两任务",
        "description": "极简输入「学英语和健身」应拆为 1-3 个任务，允许零子任务。",
        "input": "学英语和健身",
        "source": "synthetic",
        "added_in": "0.1.0",
        "rationale": "子任务数量契约下界（0）：极简输入不应被迫编造子任务。",
        "today": GOLDEN_ANCHOR_DATE,
        "plan": "学英语和健身",
    },
]
